// src/lib/components/common/SearchBar.svelte
<script lang="ts">
    import { Cosmo } from '$lib/data/apis';
    import { isAddress } from 'ethers';
	import { goto } from '$app/navigation';
    import search_icon from '$lib/assets/icons/search.svg';

    let query: string;
    let timeout: number;
    let value: string;
    let results: Cosmo.User[] | undefined;
    let searchBar: HTMLDivElement;

    function input() {
        if (timeout)
            window.clearTimeout(timeout);
        timeout = window.setTimeout(search, 150);
        results = undefined;
    }

    async function search() {
        if (!value)
            return;

        query = value;

        if (value && isAddress(value)) {
            const res = await fetch(`${Cosmo.URL}/user/v1/by-address/${query}`);
            const data = await res.json();
            if (value === query)
                results = data;
        } else if (value.length >= 4 && value.length <= 15) {
            const res = await fetch(`${Cosmo.URL}/user/v1/search?query=${query}`);
            const data = await res.json();
            if (value === query)
                results = data.results;
        }
    }

    function keypress(event: KeyboardEvent) {
        if (event.key === 'Enter' && value)
            goto(`/@${value}`);
    }

    function mouseup(e: MouseEvent) {
        if (!searchBar.contains(e.target as Node)) {
            results = undefined;
            value = '';
        }
    }
</script>

<svelte:window on:mouseup={mouseup}/>

<div class="searchBar" bind:this={searchBar}>
    <img src={search_icon} alt="Search">
    <input type="text" placeholder="Search users by ID or address" on:input={input} on:keypress={keypress} bind:value>
    {#if results && results.length}
        <div class="results">
            {#each results as result}
                <a href="/@{result.nickname}">
                    <img src="https://static.cosmo.fans/uploads/images/img_profile_gallag@3x.png" alt="{result.nickname}">
                    {result.nickname}
                </a>
            {/each}
        </div>
    {/if}
</div>

<style>
    .searchBar {
        height: 30px;
        border-radius: 15px;
        background-color: var(--search-bar-color);
        margin-left: auto;
        display: flex;
        gap: 5px;
        padding: 5px 10px;
        position: relative;
    }

    .searchBar:has(input:focus) {
        border: 1px var(--accent-color) solid;
        padding: 4px 9px;
        box-shadow: var(--box-shadow);
    }

    input {
        height: 100%;
        flex: 1;
        background: none;
        padding: 0;
        border: 0;
        outline: none;
        font-size: 16px;
    }

    .results {
        position: absolute;
        top: calc(100% + 5px);
        left: 0;
        width: 100%;
        background-color: var(--search-bar-color);
        color: #000;
        border-radius: 15px;
        box-shadow: var(--box-shadow);
        animation: fade-in 0.1s;
        max-height: 350px;
        overflow-y: scroll;
        padding: 5px 0;
    }

    .results a {
        display: flex;
        width: 100%;
        color: inherit;
        padding: 10px 15px;
        align-items: center;
        gap: 10px;
        transition: background-color 0.1s;
    }

    .results a:hover {
        background-color: #0000001A;
    }

    .results a img {
        height: 25px;
    }
</style>

// src/components/SearchBar.vue
<template>
    <div class="searchBar" ref="searchBar">
        <input type="text" class="searchBox" placeholder="Search by nickname or address" ref="searchBox"
            @keyup.enter="e => { $router.push(`/@${e.target.value}`); clear() }" @input="e => search(e.target.value)">
        <div v-if="suggestions" class="searchSuggestions">
            <RouterLink v-for="suggestion in suggestions" :to="`/@${suggestion.nickname}`" class="suggestion" @click="clear()">
                <img :src="suggestion.profileImageUrl ? suggestion.profileImageUrl : DEFAULT_PFP">
                <p>{{ suggestion.nickname }}</p>
            </RouterLink>
        </div>
    </div>
    <img class="searchIcon" ref="searchIcon" src="@/assets/icons/searchnav.svg" @click="toggleDisplay()">
</template>

<script>
export default {
    data() {
        return {
            timeout: null,
            suggestions: null
        }
    },
    mounted() {
        document.addEventListener('click', this.handleClick)
    },
    unmounted() {
        document.removeEventListener('click', this.handleClick)
    },
    methods: {
        search(query) {
            clearTimeout(this.timeout)
            this.timeout = setTimeout(async () => {
                if (!query && query.length < 4 && !query.startsWith('0x')) {
                    this.suggestions = null
                    return
                }
                const res = await fetch(`${this.COSMO_API}/user/v1/search?query=${query}`)
                const data = await res.json()
                this.suggestions = data.results
            }, 500)
        },
        handleClick(event) {
            if (!this.$refs.searchBox.contains(event.target))
                this.suggestions = null
        },
        clear() {
            clearTimeout(this.timeout)
            this.$refs.searchBox.value = null
            if (this.$refs.searchBar.classList.contains('showBar'))
                this.$refs.searchBar.classList.remove('showBar')
        },
        toggleDisplay() {
            this.$refs.searchBar.classList.toggle('showBar')
        }
    }
}
</script>

<style scoped>
.searchBar {
    position: relative;
}

.searchBox {
    font-family: inherit;
    font-size: 18px;
    padding: 5px;
    padding-left: 30px;
    border-radius: 10px;
    border: none;
    outline: none;
    background-image: url('@/assets/icons/search.svg');
    background-repeat: no-repeat;
    background-size: 20px 20px;
    background-position: 6px 6px;
    height: 30px;
    max-width: 300px;
    background-color: #F4F5F7;
    color: #000000;
}

::placeholder {
    color: #2A333A;
}

.searchSuggestions {
    position: absolute;
    top: 30px;
    width: 300px;
    max-height: 250px;
    overflow-y: scroll;
    border-radius: 10px;
    background-color: #F4F5F7;
    color: #000000;
    margin-top: 2px;
    z-index: 1;
}
.suggestion {
    width: 100%;
    height: 40px;
    display: flex;
    padding: 10px;
    gap: 10px;
    align-items: center;
    transition: background-color 0.1s;
}

.suggestion:hover {
    background-color: rgba(0, 0, 0, 0.1);
}

.suggestion img {
    height: 100%;
}

a {
    color: inherit;
}

.searchIcon {
    display: none;
    cursor: pointer;
}

.searchBar, .searchIcon {
    margin-left: auto;
}

@media only screen and (max-width: 700px) {
    .searchBar, .searchIcon {
        margin-left: 0;
    }
}

@media only screen and (max-width: 900px) {
    .searchBar {
        display: none;
        order: 99;
        flex-basis: 100%;
        justify-content: center;
        margin-bottom: 10px;
    }
    .searchIcon {
        display: initial;
    }
    .showBar {
        display: flex;
    }
}
</style>
